# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c4PauhxVEVtsUATvJsqIBQ20FVUv3ALt
"""

# Install OpenCV if needed
!pip install opencv-python

import cv2
from google.colab.patches import cv2_imshow

# Read an image
img = cv2.imread("photo1.jpg")

# Check whether the image is loaded
if img is None:
    print("Error: Image not found.")
else:
    # Get original dimensions
    height, width = img.shape[:2]

    # Resize to 50% of original size
    resized_img = cv2.resize(img, (width, height))

    # Display resized image
    cv2_imshow(resized_img)

import cv2
from google.colab.patches import cv2_imshow

# Read image in grayscale
img = cv2.imread("photo1.jpg", 0)

if img is None:
    print("Image not found!")
else:
    # Automatic threshold using Otsu
    ret, binary = cv2.threshold(
        img, 0, 255,
        cv2.THRESH_BINARY + cv2.THRESH_OTSU
    )

    # Display original
    cv2_imshow(img)

    # Display binary
    cv2_imshow(binary)

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read image
img = cv2.imread("photo1.jpg")

# Split channels
b, g, r = cv2.split(img)

# Create blank channel
zeros = np.zeros_like(b)

# Create colored channel images
red_img = cv2.merge([zeros, zeros, r])
green_img = cv2.merge([zeros, g, zeros])
blue_img = cv2.merge([b, zeros, zeros])

print("Original Image")
resized_img = cv2.resize(img, (width//8, height//8))
cv2_imshow(resized_img)

print("Red Channel")
resized_img = cv2.resize(red_img, (width//8, height//8))
cv2_imshow(resized_img)

print("Green Channel")
resized_img = cv2.resize(green_img, (width//8, height//8))
cv2_imshow(resized_img)

print("Blue Channel")
resized_img = cv2.resize(blue_img, (width//8, height//8))
cv2_imshow(resized_img)

