# -*- coding: utf-8 -*-
"""CV-CO1-AT1-Q02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NorttnghLHzTvD2GB-ioU-L1W_DqmUHV
"""

import cv2  # Import OpenCV for image processing algorithms
import numpy as np                                           # Import Numpy for mathematical matrix operations
import matplotlib.pyplot as plt                              # Import Matplotlib to visualize the output on screen

# Step 1: Create a synthetic image representing a clear scene
img = np.zeros((100, 100), dtype=np.uint8)  # Create a blank black image array filled with zeros
cv2.circle(img, (50, 50), 30, 200, -1)  # Draw a filled or outlined circle on the image

# Step 2: Simulate low light by drastically reducing contrast and brightness
low_light = cv2.convertScaleAbs(img, alpha=0.2, beta=0)  # Scale and shift pixel values, clamp to 0-255

# Step 3: Apply Histogram Equalization to mathematically stretch the contrast
enhanced = cv2.equalizeHist(low_light)  # Enhance contrast using histogram equalization

# Step 4: Display the final enhanced image
plt.figure(figsize=(8,4))  # Create a new figure window for display
plt.subplot(121), plt.imshow(low_light, cmap='gray'), plt.title('Low Light Image')  # Place this image in a subplot grid position
plt.subplot(122), plt.imshow(enhanced, cmap='gray'), plt.title('Enhanced via Equalization')  # Place this image in a subplot grid position
plt.show()  # Show the final plot window to the user
